### DISCUSSION TITLE
Running a IHP app build on github actions

### DISCUSSION THREAD

**Discussion by francisdb** [digitallyinduced/ihp#1292] [Q&A] [answered]
Hi,

I would like to set up a CI build for my IHP project, any hints on how to do that? 

I found https://github.com/marketplace/actions/install-nix

But not sure how that applies to a IHP project?

**Comment by mpscholten** [comment]
Here's one github action file that builds an IHP app and then uses nix to copy it over to the production server. At the end the github action switches a symlink at `/root/app` to the deployed build and restarts the services:

```yml
name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install nix and cachix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/51bcdc4cdaac48535dabf0ad4642a66774c609ed.tar.gz
      - name: Cachix Init
        uses: cachix/cachix-action@v10
        with:
          name: digitallyinduced
          skipPush: true
      - name: "Building"
        run : nix-build -j auto --cores 0
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa
          config: |
            Host production
                    HostName REPLACEME.eu-central-1.compute.amazonaws.com
                    User root
                    IdentityFile ~/.ssh/id_rsa
      - name: "Copying Build"
        run : nix --experimental-features nix-command copy --to ssh://production ./result
      - name: "Migrate DB"
        run: |
          nix-shell --run migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: "Enable Build"
        run: ssh production "ln -sfT $(readlink -f ./result) /root/app"
      - name: "Restart App"
        run: ssh production "systemctl restart app worker"
```

If you don't want to deploy the binary, remove all steps after `      - name: "Building"`.

For completeness here's also a nix file that fits the above github action:

```nix
let
    ihpEnv = {
            PORT = "8000";
            IHP_REQUEST_LOGGER_IP_ADDR_SOURCE = "FromHeader";
            IHP_BASEURL = "https://someapp.digitallyinduced.com";
            IHP_ENV = "Production";
            DATABASE_URL = "REPLACEME";
            IHP_SESSION_SECRET = "REPLACEME";
        };
in
{ config, pkgs, modulesPath, ... }: {
    imports = [ "${modulesPath}/virtualisation/amazon-image.nix" ];
    ec2.hvm = true;
    environment.systemPackages = with pkgs; [
        vim
    ];
    i18n.defaultLocale = "en_US.UTF-8";
    console = {
        font = "Lat2-Terminus16";
        keyMap = "us";
    };
    nix = {
        binaryCaches = [ "https://digitallyinduced.cachix.org" ];
        binaryCachePublicKeys = [ "digitallyinduced.cachix.org-1:y+wQvrnxQ+PdEsCt91rmvv39qRCYzEgGQaldK26hCKE=" ];
    };


    systemd.services.app = {
        enable = true;
        description = "App";
        serviceConfig = {
            Type = "simple";
            ExecStart = "/root/app/bin/RunProdServer";
            WorkingDirectory = "/root/app/lib";
        };
        environment = ihpEnv;
    };

    systemd.services.worker = {
        enable = true;
        description = "Worker";
        serviceConfig = {
            Type = "simple";
            ExecStart = "/root/app/bin/RunJobs";
            WorkingDirectory = "/root/app/lib";
        };
        environment = ihpEnv;
    };

    services.nginx = {
        enable = true;
        enableReload = true;
        recommendedProxySettings = true;
        recommendedGzipSettings = true;
        recommendedOptimisation = true;
        recommendedTlsSettings = true;
        virtualHosts."someapp.digitallyinduced.com" = {
            forceSSL = true;
            enableACME = true;
            locations = {
                "/" = { proxyPass = "http://app_upstream"; proxyWebsockets = true; };
            };
        };
        appendHttpConfig = ''
            upstream app_upstream { server localhost:8000; }
        '';
    };

    networking.firewall.allowedTCPPorts = [ 80 443 22 ];

    security.acme.email = ''support@digitallyinduced.com'';
    security.acme.acceptTerms = true;
}
```

**Reply by francisdb** [reply]
thanks!

**Reply by stephenbenedict** [reply]
Thank you for sharing this. I'm trying to adapt this to my own workflow (deploying to a VPS) but am confused by this part:

```
   - name: "Copying Build"
        run : nix --experimental-features nix-command copy --to ssh://production ./result
```

What does that do?

**Reply by mpscholten** [reply]
The `./result` is a symlink to the build stored inside `/nix/store`. So something like `/nix/store/blabla`.

The `nix copy` command copies over the nix output derivation (the output of the `nix-build`) over to the production server then (it also copies all required dependencies as well). Now the production server has a path `/nix/store/blabla` where the result of the `nix-build` is stored.

**Reply by stephenbenedict** [reply]
Thanks. I understand now.

**Comment by francisdb** [comment]
One more related question:
How would I run the tests in the CI build?

**Reply by mpscholten** [reply]
A build step like this should do it:
```yml
    tests:
     name: Run Tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2.3.4
     - uses: cachix/install-nix-action@v12
       with:
         nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c7f75838c360473805afcf5fb2fa65e678efd94b.tar.gz
     - uses: cachix/cachix-action@v8
       with:
         name: digitallyinduced
         skipPush: true
     - run: |
           cd $GITHUB_WORKSPACE
           mkdir -p ~/.config/nixpkgs
           echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
           nix-shell --run "runghc $(make print-ghc-extensions) $(make print-ghc-options) Tests/Main.hs"
```

**Comment by francisdb** [comment]
Still having problems:


(I printed both make commands)
```
Warning: haddock-html: /nix/store/4jwl6wwy923lvh77h10p6adyfiqjd1a1-bytestring-builder-0.10.8.2.0/share/doc/x86_64-linux-ghc-8.10.7/bytestring-builder-0.10.8.2.0/html doesn't exist or isn't a directory
-XOverloadedStrings -XNoImplicitPrelude -XImplicitParams -XRank2Types -XDisambiguateRecordFields -XNamedFieldPuns -XDuplicateRecordFields -XOverloadedLabels -XFlexibleContexts -XTypeSynonymInstances -XFlexibleInstances -XQuasiQuotes -XTypeFamilies -XPackageImports -XScopedTypeVariables -XRecordWildCards -XTypeApplications -XDataKinds -XInstanceSigs -XDeriveGeneric -XMultiParamTypeClasses -XTypeOperators -XDeriveDataTypeable -XMultiWayIf -XUndecidableInstances -XBlockArguments -XPartialTypeSignatures -XLambdaCase -Wno-unsafe -Wno-name-shadowing -Wno-monomorphism-restriction -Wno-safe -Wno-missing-local-signatures -Wno-missing-home-modules -XDefaultSignatures -XEmptyDataDeriving -XBangPatterns -XBlockArguments -XMultiWayIf -XFunctionalDependencies -fbyte-code -Wno-partial-type-signatures -XPartialTypeSignatures -XStandaloneDeriving -XDerivingVia -Werror=missing-fields -fwarn-incomplete-patterns -XTemplateHaskell
-threaded -i. -ibuild -iConfig -iIHP -iIHP/IDE -XOverloadedStrings -XNoImplicitPrelude -XImplicitParams -XRank2Types -XDisambiguateRecordFields -XNamedFieldPuns -XDuplicateRecordFields -XOverloadedLabels -XFlexibleContexts -XTypeSynonymInstances -XFlexibleInstances -XQuasiQuotes -XTypeFamilies -XPackageImports -XScopedTypeVariables -XRecordWildCards -XTypeApplications -XDataKinds -XInstanceSigs -XDeriveGeneric -XMultiParamTypeClasses -XTypeOperators -XDeriveDataTypeable -XMultiWayIf -XUndecidableInstances -XBlockArguments -XPartialTypeSignatures -XLambdaCase -Wno-unsafe -Wno-name-shadowing -Wno-monomorphism-restriction -Wno-safe -Wno-missing-local-signatures -Wno-missing-home-modules -XDefaultSignatures -XEmptyDataDeriving -XBangPatterns -XBlockArguments -XMultiWayIf -XFunctionalDependencies -fbyte-code -Wno-partial-type-signatures -XPartialTypeSignatures -XStandaloneDeriving -XDerivingVia -Werror=missing-fields -fwarn-incomplete-patterns -XTemplateHaskell -j -package-env - +RTS -A256m -n2m -N --RTS -package ihp -rtsopts=all
dirname: missing operand
Try 'dirname --help' for more information.
Makefile:22: /../lib/IHP/Makefile.dist: No such file or directory
make: *** No rule to make target '/../lib/IHP/Makefile.dist'.  Stop.
dirname: missing operand
Try 'dirname --help' for more information.
Makefile:22: /../lib/IHP/Makefile.dist: No such file or directory
make: *** No rule to make target '/../lib/IHP/Makefile.dist'.  Stop.
```

**Reply by mpscholten** [reply]
Are you using the latest IHP version? Can you share the github action step that is failing?

**Reply by francisdb** [reply]
I updated the nixpkgs and action versions compared to your example

```
let
    ihp = builtins.fetchGit {
        url = "https://github.com/digitallyinduced/ihp.git";
        ref = "refs/tags/v0.17.0";
    };
    haskellEnv = import "${ihp}/NixSupport/default.nix" {
        ihp = ihp;
        haskellDeps = p: with p; [
            cabal-install
            base
            wai
            text
            hlint
            p.ihp
            hspec
        ];
        otherDeps = p: with p; [
            # Native dependencies, e.g. imagemagick
        ];
        projectPath = ./.;
    };
in
    haskellEnv

```

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/51bcdc4cdaac48535dabf0ad4642a66774c609ed.tar.gz
      - name: Cachix Init
        uses: cachix/cachix-action@v10
        with:
          name: digitallyinduced
          skipPush: true
      - name: "Building"
        run : nix-build -j auto --cores 0      

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p ~/.config/nixpkgs
          echo "{ allowBroken = true; }" >> ~/.config/nixpkgs/config.nix
          nix-shell --run "make print-ghc-extensions"
          nix-shell --run "make print-ghc-options"
          nix-shell --run "runghc $(make print-ghc-extensions) $(make print-ghc-options) Test/Main.hs"      

```
