### ISSUE TITLE
enable only docs workflow when changes made to md files

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1845]
When changes are made to markdown files all workflows are run. Ideally, in such a scenario we should only run the the [docs workflow](https://github.com/digitallyinduced/ihp/blob/master/.github/workflows/docs.yml). We can do so by using something like this on all other workflows:

```
on:
  push:
    paths:
      - '**/*'
      - '!**/*.md'  # Exclude Markdown files
 ```
 
 Thoughts?
